apiVersion: v1 # API 버전 지정
kind: Service # 리소스 종류를 Service로 지정

metadata:
  name: sample-cd-clusterip # Service 이름 지정

spec:
  type: ClusterIP # 서비스 타입을 ClusterIP로 지정
  ports:
    - name: "http-port" # 포트 이름 지정
      protocol: "TCP" # 프로토콜을 TCP로 설정
      port: 8080 # 서비스에서 사용하는 포트 번호
      targetPort: 80 # 실제 Pod의 컨테이너가 사용하는 포트 번호
  selector:
    app: sample-cd-app # Deployment의 레이블과 일치해야 함

